### ISSUE TITLE
Mod Broken by the Update 8

### ISSUE THREAD

**Issue by untanya** [Sylwesterlew/SatisfactoryFastConveyors#2]
Hi,
Would it be possible to revisit the mod to make it compatible with Satisfactory's Update 8?
It would be greatly appreciated, thank you very much!

![image](https://github.com/user-attachments/assets/b31249b7-652b-4b9c-933a-f159316d2c96)

**Comment by Sylwesterlew** [comment]
Hi @untanya 
thx for using my mod but there is no more sense to update it because someone created much better mod for that
https://ficsit.app/mod/EnhancedConveyors
