### ISSUE TITLE
Mod no longer available on https://ficsit.app/mods

### ISSUE THREAD

**Issue by OFCR10PENNY** [Sylwesterlew/SatisfactoryFastConveyors#3]
Hi, the mod no longer exists on the mod page or in the satisfactory mod manager.
I am currently playing on U7, the game force updated for me a few days ago to 1.0 which made me lose all my mods, including the FastConveyors mod. Since i dont know how to compile your mod thats on github, could you upload it again on the ficsit mod page?

**Comment by Sylwesterlew** [comment]
Hi @OFCR10PENNY 
thx for using my mod but after release 1.0 this mod is not compatibile anymore and someone created much better mod for that
https://ficsit.app/mod/EnhancedConveyors

**Comment by OFCR10PENNY** [comment]
Thanks for your reply. 

I know that the mod is not compatible with 1.0 and im not asking you to update the mod. As I said before, I am still playing on update 7, and as I remember the mod was compatible with U7. The other mod that you refered to "https://ficsit.app/mod/EnhancedConveyors" is not available for U7 as the mod does not support SML 3.4.1.

I just wondered if you could reupload the mod on ficsit.app since me and a lot of other people prefer to play on older versions of satisfactory. And honestly, your mod was probably the best conveyor mod that I have used.

**Comment by Sylwesterlew** [comment]
I'm sorry for removed it but I didn't realize someone could still using it. I didn't know you can even choose to play other version than latest update. Unfortunately I don't have old compiled version. Also I don't have configured enviroment to compile it again and don't know if it is still posible to do that for old update
